name: Lint & Test

on:
  push:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop --command bash {0}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: nixbuild/nix-quick-install-action@v25
        with:
          nix_conf: |
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            keep-outputs = true

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v1
        with:
          linux-gc-enabled: true
          linux-max-store-size: 536870912
          key: ${{ runner.os }}-nix-${{ hashFiles('**/flake.nix', '**/flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test
