name: Lint & Test

on:
  push:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop --command bash {0}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install the Nix package manager
        uses: cachix/install-nix-action@v20

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
