name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop --command bash {0}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install the Nix package manager
        uses: cachix/install-nix-action@v20

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'release: version packages'
          version: nix develop --command pnpm version-package
          publish: nix develop --command pnpm publish-package
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
